version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    hostname: db
    container_name: db-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass0100
      - MYSQL_DATABASE=berrydb
      - MYSQL_USER=berry
      - MYSQL_PASSWORD=pass0100
      - TZ=Asia/Seoul    
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
