server:
  servlet:
    context-path: "/api"
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/berrydb?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: berry
    password: pass0100
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
